### ISSUE TITLE
can't send binary data in POST request

### ISSUE THREAD

**Issue by veksha** [treeform/puppy#19]
this works:
```nim
  req.body = @[byte 32,32,32,32]  # just spaces
```

this doesn't:
```nim
  req.body = @[byte 0,0,32,32]
```
### Current behavior:
request (WinHttp.WinHttpRequest.5.1) will be sent with an empty (or truncated) body and content-length header will be changed accordingly.

### What I've tried:
editing puppy.nim like this:
```nim
		let AStream = CreateObject("ADODB.Stream")
        AStream.Type = 1 # binary
        AStream.Mode = 2 # write mode
        AStream.Open()
        AStream.Write( toVariant(COMBinary req.body) ) #Write data to stream object
        AStream.Flush()  
        
        obj.send(AStream)
```
No luck!
Don't know how to work with COM so I need your help :)

PS: in libcurl mode - same thing.
EDIT: had to add `curl.easy_setopt(OPT_POSTFIELDSIZE_LARGE, req.body.len)` to make it somewhat work, but still getting SIGSEGV on `curl.easy_perform()`

**Comment by treeform** [comment]
Thank you for reporting the bug.

I think we fixed this. Can you try and confirm?

**Comment by treeform** [comment]
Feel free to reopen if its still an issue.

**Comment by guzba** [comment]
Puppy version 1.2.1 tested with this fixed. As treeform said, pls reopen if issues remain.
